# Generated by Django 6.1 on 2026-09-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0002_tenant_domain_prefix_alter_tenant_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='batchdegreeenrollment',
            unique_together={('batch', 'degree_program')},
        ),
        migrations.AlterUniqueTogether(
            name='degreeprogram',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='moduledegreemapping',
            unique_together={('module', 'degree_program')},
        ),
        migrations.AlterUniqueTogether(
            name='modulelecturer',
            unique_together={('module', 'lecturer')},
        ),
    ]
