# Generated by Django 6.1 on 2026-09-10 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='batchdegreeenrollment',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree_enrollments', to='academics.batch'),
        ),
        migrations.AddField(
            model_name='degreeprogram',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree_programs', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='batchdegreeenrollment',
            name='degree_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_enrollments', to='academics.degreeprogram'),
        ),
        migrations.AddField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='degreeprogram',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree_programs', to='academics.department'),
        ),
        migrations.AddField(
            model_name='groupbatchmapping',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_mappings', to='academics.batch'),
        ),
        migrations.AddField(
            model_name='hall',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturers', to='academics.department'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturers', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lectureravailability',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='academics.lecturer'),
        ),
        migrations.AddField(
            model_name='module',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='academics.department'),
        ),
        migrations.AddField(
            model_name='module',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='moduledegreemapping',
            name='degree_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_mappings', to='academics.degreeprogram'),
        ),
        migrations.AddField(
            model_name='moduledegreemapping',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree_mappings', to='academics.module'),
        ),
        migrations.AddField(
            model_name='modulelecturer',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_lecturers', to='academics.lecturer'),
        ),
        migrations.AddField(
            model_name='modulelecturer',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_lecturers', to='academics.module'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='groupbatchmapping',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_mappings', to='academics.studentgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='batchdegreeenrollment',
            unique_together={('batch', 'degree_program')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='degreeprogram',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='hall',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='moduledegreemapping',
            unique_together={('module', 'degree_program')},
        ),
        migrations.AlterUniqueTogether(
            name='modulelecturer',
            unique_together={('module', 'lecturer')},
        ),
    ]
