# Generated by Django 6.1 on 2026-09-02 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_batch_unique_together_and_more'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='degree_program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.degreeprogram'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('batch', 'degree_program', 'version')},
        ),
    ]
